U = "Press not yet identified"
items3 = [
 ("0073","South Indian composite print","Temple deities and scenes in many panels","South India","south","","","worn frame",""),
 ("0074","Deity rising from the ocean","A multi-armed deity above the water",U,"other","","","severe losses and flaking",""),
 ("0075","Vishnu with Sridevi and Bhudevi","Vishnu under the serpent hood with both consorts",U,"other","","","good, strong colours","Same composition as no. 0015."),
 ("0076","Worship of the Shiva linga","Rama and Sita worship the linga at Rameswaram, with Hanuman and sages","South India","south","","","good",""),
 ("0077","Dasharatha and Kaikeyi","The grieving king on his bed, Kaikeyi and the young prince",U,"other","","","good",""),
 ("0078","King and queen in a palace","A seated king takes the hand of a standing queen",U,"other","","","good","Subject still to be identified."),
 ("0079","Krishna with cow, advertising print","Krishna with cow and deer in a landscape","Advertising print for V. S. & Sons, Kumbakonam","south","","","good",""),
 ("0080","Coronation of Rama","Rama and Sita enthroned with brothers and Hanuman",U,"other","","","heavy losses",""),
 ("0081","Vishnu on the lotus, advertising print","Vishnu standing on a lotus under the serpent hood","Advertising print for Sri Ramakrishna Vilas, Kumbakonam. Reg. no. 4065","south","","","good",""),
 ("0082","Krishna with flute","Krishna under the tree with gopis and cows, South Indian style",U,"other","","","fair","Same composition as no. 0011."),
 ("0083","Krishna in the cradle","The infant Krishna in a swinging cradle, with Yashoda and women",U,"other","","","good",""),
 ("0084","Woman on a swing","A young woman on a swing high above a valley, a Ravi Varma composition",U,"other","","","good",""),
 ("0085","Deity in a temple gateway","A standing deity in a temple gateway, with cherubs above","South India","south","","","worn frame",""),
 ("0086","Ganesha enthroned","Ganesha seated on his throne with his mouse",U,"other","","","good",""),
 ("0087","Lakshmi on the lotus","Lakshmi seated on the lotus with a radiant halo",U,"other","","","fair, later print",""),
 ("0088","Menaka and Shakuntala","Menaka carries the infant Shakuntala through the clouds, signed Ravi Varma",U,"other","","","good",""),
 ("0089","Krishna with consorts, Tanjore style","Plump Krishna enthroned with two consorts","South India","south","","","fair","Same composition as no. 0025."),
 ("0090","Nataraja","Shiva as lord of dance with Sivakami, in a temple setting","South India","south","","","good",""),
 ("0091","Shiva's family with gods, embellished","Shiva and Parvati with Ganesha, flanked by deities, applied decoration",U,"other","","","fair","Hand-embellished."),
 ("0092","Usha and Chitralekha","Chitralekha shows the dreaming Usha a portrait, probably of Aniruddha",U,"other","","","good",""),
 ("0093","Dasha Mahavidya, sheet 2","Five of the ten wisdom goddesses in roundels, Bengali captions","Probably Calcutta, Bengal school","bengal","","","fair","Belongs together with no. 0096."),
 ("0094","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","good",""),
 ("0095","South Indian composite print","Temple deities and scenes from the Ramayana in many panels","South India","south","","","good",""),
 ("0096","Dasha Mahavidya, sheet 1","Five of the ten wisdom goddesses in roundels, Kamala in the centre, Bengali captions","Probably Calcutta, Bengal school","bengal","","","fair","Belongs together with no. 0093."),
 ("0097","Death of Vali","Rama with bow beside the fallen Vali, surrounded by monkeys",U,"other","","","fair",""),
 ("0098","Saraswati, embellished","Saraswati with veena and peacock, applied decoration",U,"other","","","fair","Hand-embellished."),
 ("0099","Young woman by a tree","A young woman leaning on a tree with a basket, a Ravi Varma composition",U,"other","","","good",""),
 ("0100","Ganesha receives the elephant head","The child Ganesha on an altar surrounded by gods, Shiva and Parvati",U,"other","","","glass damaged",""),
 ("0101","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","crack in the glass",""),
 ("0102","Rama and Sita meet in the garden","Rama and Lakshmana see Sita and her companions in the garden of Mithila",U,"other","","","losses at the top",""),
 ("0103","Murugan of Palani","Murugan as young ascetic with staff, the Palani temple in the corner","South India","south","","","fair",""),
 ("0104","Rama, Sita and Lakshmana at the hut","The exiles by their forest hut at a stream",U,"other","","","fair",""),
 ("0105","Murugan with Valli and Deivanai","Six-headed Murugan in a shrine between his two consorts","South India","south","","","good",""),
 ("0106","Worship of the Shiva linga","Rama and Sita worship the linga at Rameswaram, with Hanuman and sages","South India","south","","","fair",""),
 ("0107","Shakuntala with her friends","Shakuntala with Anasuya and Priyamvada, a deer at her side",U,"other","","","good",""),
 ("0109","Shiva's family with gods","Shiva and Parvati with Ganesha, flanked by deities",U,"other","","","good","Same composition as no. 0091."),
 ("0110","Vishvamitra and Menaka","The nymph Menaka approaches the meditating sage Vishvamitra",U,"other","","","good",""),
 ("0111","Ganesha with attendants","Ganesha enthroned among women with fly whisks and veenas",U,"other","","","good",""),
 ("0112","Virabhadra at Daksha's sacrifice","A fierce figure with sword at the altar, Sati's spirit above, Nandi",U,"other","","","good","Subject probable, to be confirmed."),
 ("0113","Rama lifts Shiva's bow","Rama with the great bow at Sita's bridegroom contest, onlookers at a temple",U,"other","","","good","Subject probable, to be confirmed."),
 ("0114","Ganesha with Riddhi and Siddhi","Ganesha under a parasol with his two consorts",U,"other","","","fair",""),
 ("0115","Lakshmi on the lotus","Lakshmi on the lotus with elephant, palm trees behind",U,"other","","","good",""),
 ("0116","Yashoda and Krishna","Yashoda milks a cow while the child Krishna clings to her",U,"other","","","good","Print after the Ravi Varma painting that set an auction record in April 2026."),
 ("0117","Dattatreya, advertising print","Three-headed Dattatreya with cow and dogs","Advertising print for T. S. R. & Co., Kumbakonam","south","","","worn frame",""),
 ("0118","Sai Baba of Shirdi","Sai Baba seated on a rock, Dattatreya behind",U,"other","","","fair, later print",""),
 ("0119","Goddess with gold embossing","A four-armed goddess enthroned, Hindi captions, embossed gold",U,"other","","","good",""),
 ("0120","Shiva and Parvati with Nandi, advertising print","Shiva and Parvati in the Himalaya","Advertising print for Sri Ambika Silk Stores, Tanjore","south","","","fair, later print",""),
]
dups3 = {"0108":"0107"}
