U = "Press not yet identified"
B = "Probably Calcutta, Bengal school"
items6 = [
 ("0246","Durga slays Mahishasura","Durga on her lion kills the buffalo demon",U,"other","","","good","Same composition as no. 0069."),
 ("0247","Worship of the Shiva linga","Rama and Sita worship the linga at Rameswaram, with Hanuman and sages","South India","south","","","fold and losses",""),
 ("0248","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans, caption strip visible",U,"other","","","good",""),
 ("0249","Krishna with consorts, Tanjore style","Plump Krishna enthroned with two consorts","South India","south","","","fair","Same composition as no. 0025."),
 ("0250","Lakshmi on the lotus","Lakshmi on the lotus with elephant, advertising roundel at top right",U,"other","","","fair, sepia tones",""),
 ("0251","Ardhanarishvara","Shiva and Parvati united in one body, with lion and bull",U,"other","","","good","A well-known Ravi Varma composition."),
 ("0252","Rama worships Durga","Rama offers his eye to Durga before the battle, Hanuman and Vibhishana beside",B,"bengal","","","good",""),
 ("0253","Kali on Shiva","Kali stands on the prostrate Shiva on the battlefield",B,"bengal","","","good",""),
 ("0254","Rama enthroned with his allies","Rama and Sita enthroned with Vibhishana, Sugriva and Jambavan",U,"other","","","good",""),
 ("0255","Krishna with gopis in the grove","Krishna among gopis beneath a tree with peacocks",U,"other","","","fair",""),
 ("0256","Dakshina Kali","The Kali image in a shrine with curtains",B,"bengal","","","fair","Belongs together with no. 0257."),
 ("0257","Dakshina Kali","The Kali image in a shrine under a canopy",B,"bengal","","","fair","Belongs together with no. 0256."),
 ("0258","Durga with her family","Durga on her lion with Lakshmi, Saraswati, Ganesha and Kartikeya",B,"bengal","","","good",""),
 ("0260","Kali on Shiva","Kali stands on the prostrate Shiva on the battlefield",B,"bengal","","","good","Same composition as no. 0253."),
 ("0261","Dasha Mahavidya","The ten wisdom goddesses in panels around Durga",B,"bengal","","","good",""),
 ("0262","Shiva with scenes of human life","Shiva in the centre, scenes from birth to death around him",B,"bengal","","","good",""),
 ("0263","Jagannath, Balabhadra and Subhadra","The three deities of Puri in their shrine",B,"bengal","","","good",""),
 ("0264","Krishna steals the gopis' clothes","Krishna in the tree with the clothes, the gopis in the water",B,"bengal","","","good",""),
 ("0265","Shodashi","The goddess enthroned on a couch above Shiva, gods below",B,"bengal","","","heavy losses",""),
 ("0266","Ganesha","Ganesha seated under a canopy",B,"bengal","","","good",""),
 ("0267","Annapurna gives alms to Shiva","Shiva as a beggar before the enthroned Annapurna",B,"bengal","","","good",""),
 ("0268","Couple on a palace terrace","A prince and a woman embrace by the columns, Bengali caption",B,"bengal","","","good","Subject still to be identified."),
 ("0269","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Brahma on the lotus",B,"bengal","","","good",""),
 ("0270","Shiva with sacred sites","Shiva in the centre, surrounded by ovals with temples and saints",B,"bengal","","","fair",""),
 ("0272","Radha and Krishna","Krishna plays the flute, Radha leans on him",U,"other","","","worn frame",""),
 ("0273","Shiva's family","Shiva and Parvati with Ganesha, Nandi, lion and sages",U,"other","","","creased",""),
 ("0274","South Indian composite print","Temple deities and scenes in many panels","South India","south","","","fair",""),
 ("0276","Nala leaves Damayanti","Nala sits beside the sleeping Damayanti in the forest",U,"other","","","good","Landscape format."),
 ("0277","Krishna and Balarama with cows","The brothers with cowherds and cows under a tree",B,"bengal","","","good","Landscape format."),
 ("0278","Rasa Lila by moonlight","Many Krishnas dance with the gopis on a moonlit riverbank",U,"other","","","good","Landscape format."),
 ("0280","Panchanana Shiva","Five-headed Shiva seated on a lotus",B,"bengal","","","good","Gilt frame."),
 ("0281","Rama, Sita and Lakshmana at the hut","The exiles by their forest hut, a golden deer nearby",B,"bengal","","","good","Gilt frame."),
 ("0282","Chaitanya and Nityananda","The two Bengali saints with raised arms",B,"bengal","","","good","Gilt frame."),
 ("0283","Rama and Sita in the temple","Rama and Sita in a shrine with Lakshmana, Bharata and Hanuman",U,"other","","","good",""),
 ("0284","Dattatreya with cows","Three-headed Dattatreya in a landscape with cows",U,"other","","","losses at the top",""),
 ("0285","Rani of Jhansi","The queen on horseback with drawn sword, Marathi caption",U,"other","","","good","Nationalist subject."),
 ("0286","Chaitanya and Nityananda dancing","The two saints dancing in ecstasy",B,"bengal","","","damaged mount",""),
 ("0287","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Brahma, Garuda and Narada",U,"other","","","good",""),
 ("0288","Krishna with gopis and cows","Krishna with flute among gopis and cows under a tree",U,"other","","","good",""),
 ("0289","Krishna with two gopis","Krishna with flute between two women and calves",U,"other","","","good",""),
 ("0290","Hari-Hara Milan","Vishnu and Lakshmi on an elephant meet Shiva, Parvati and Ganesha on Nandi",U,"other","","","good","Same composition as no. 0179. Silver frame."),
 ("0291","Lady in a sari","A woman in a striped sari in a palace room",U,"other","","","crease",""),
 ("0292","Coronation of Rama, advertising print","Rama and Sita enthroned, with Marathi advertising text","Advertising print for 'Pain Killer'","other","","","fair",""),
 ("0293","Woman with broken pots and a boy","A woman with broken pots, a young boy seated beside",U,"other","","","fair","Subject still to be identified."),
 ("0294","Vishnu on Shesha with the gods","Vishnu on the serpent surrounded by gods and sages",U,"other","","","darkened",""),
 ("0295","Coronation of Rama","Rama and Sita enthroned with brothers and Hanuman",U,"other","","","torn edge",""),
 ("0296","Yashoda and Krishna","Yashoda milks a cow while the child Krishna clings to her, caption visible",U,"other","","","good","Print after the Ravi Varma painting that set an auction record in April 2026."),
 ("0297","Arjuna and Subhadra","A crowned prince with bow and a woman reading a letter",U,"other","","","good","Subject probable, after a Ravi Varma painting."),
 ("0298","Krishna and Radha with cows","Krishna with flute and Radha between two cows",U,"other","","","good",""),
 ("0299","Rama, Sita and Lakshmana go into exile","The three walk barefoot through the landscape",U,"other","","","worn frame",""),
 ("0301","Vithoba and Rakhumai","The deities of Pandharpur with saints and temple scenes around them",U,"other","","","fair",""),
 ("0302","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Narada, Garuda and Brahma",U,"other","","","good","Landscape format."),
 ("0304","Lakshmi and Saraswati in the swan boat, advertising print","The two goddesses in a boat under a parasol","Advertising print for The General Stores, Tanjore","south","","","good",""),
 ("0305","Murli Manohar","Krishna with flute by a waterfall in moonlight",U,"other","","","good",""),
 ("0306","Ganesha with Riddhi and Siddhi","Ganesha under a parasol with his two consorts",U,"other","","","crack in the glass","Same composition as no. 0114."),
 ("0307","Couple dancing in a garden","A crowned man and a woman dance, companions behind",U,"other","","","good","Gilt frame."),
 ("0308","Krishna with two gopis bearing offerings","Krishna with halo between two kneeling women",U,"other","","","good",""),
]
dups6 = {"0271":"0270","0279":"0278","0303":"0302"}
