U = "Press not yet identified"
B = "Probably Calcutta, Bengal school"
items7 = [
 ("0309","Dattatreya with a devotee","Three-headed Dattatreya as naked ascetic, a devotee kneels",U,"other","","","worn frame",""),
 ("0310","Shiva and Parvati on Nandi","Shiva and Parvati ride Nandi, attendants blow horns","Printed at an art studio in Calcutta","bengal","","","good",""),
 ("0311","Hari-Hara Milan","Vishnu and Lakshmi on an elephant meet Shiva, Parvati and Ganesha on Nandi, Bengali caption",B,"bengal","","","good","Identifies the subject of nos. 0179 and 0290."),
 ("0312","Satyanarayan Puja","Vishnu as Satyanarayan appears to a couple performing the puja with a priest",U,"other","","","fair",""),
 ("0313","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","darkened, unframed",""),
 ("0314","Saraswati, advertising calendar","Saraswati with veena and peacock, soap advertisement","Advertising calendar for a soap brand","other","1939","","good","Dated 1939 on the sheet."),
 ("0315","Coronation of Rama","Rama and Sita enthroned with courtiers, Hanuman and Jambavan",B,"bengal","","","good",""),
 ("0316","Shiva and Parvati with Narada","Shiva with veena beside Parvati, Narada behind, lion in front",B,"bengal","","","good",""),
 ("0317","Murugan as a boy, advertising print","The young Murugan with peacock in a landscape, Tamil text at the top","Advertising print, Tamil Nadu","south","","","scratches",""),
 ("0318","Vishnu image in a Kerala shrine","A four-armed Vishnu image in a green arch, Guruvayur style","South India","south","","","fair",""),
 ("0319","Vishnu on the banyan leaf","Infant Vishnu on a banyan leaf, surrounded by scenes in roundels",U,"other","","","damaged","Painted frame. Same composition as no. 0037."),
 ("0320","Radha and Krishna on lotuses","Radha and Krishna standing under a fruit tree",U,"other","","","good","Gilt frame."),
 ("0321","Hanuman carries the mountain","Hanuman flies with the mountain of healing herbs",U,"other","","","good","Same composition as no. 0215."),
 ("0322","Saraswati with swan","Saraswati with veena, peacock and swan by a river",B,"bengal","","","good",""),
 ("0323","Court scene with a woman","A crowded court with a woman in the centre, probably the disrobing of Draupadi",U,"other","","","fair","Small landscape format."),
 ("0324","Arjuna elopes with Subhadra","A couple drives off in a chariot, pursued by warriors, Bengali caption",B,"bengal","","","good","Subject probable. Landscape format."),
 ("0325","Vishnu on Shesha with the gods","Vishnu reclining with Lakshmi, gods and sages around",B,"bengal","","","good","Landscape format, gilt frame."),
 ("0326","Radha and Krishna","Krishna and Radha embrace on cushions",U,"other","","","fair",""),
 ("0327","Annapurna gives alms to Shiva","Shiva as a beggar before the enthroned Annapurna",B,"bengal","","","darkened","Same composition as no. 0267."),
 ("0328","Kali on Shiva","Kali stands on the prostrate Shiva, jackals behind",B,"bengal","","","good","Gilt frame."),
 ("0329","Vishnu on Shesha with the gods","Vishnu reclining with Lakshmi, Brahma on the lotus, gods around",U,"other","","","losses at the top","Gilt frame."),
 ("0330","Ascetic with cows","A naked bearded ascetic in a forest with cows, Devanagari caption",U,"other","","","good","Saint still to be identified. Gilt frame."),
 ("0332","Krishna teases the gopis","Krishna breaks the gopis' water pots",U,"other","","","good","Gilt frame."),
 ("0333","Shiva's family with attendants","Shiva, Parvati and Ganesha enthroned, attendants blow horns",U,"other","","","pale","Gilt frame."),
 ("0334","Ram Darbar","Rama with Sita, Lakshmana and Hanuman in a palace",U,"other","","","fair",""),
 ("0335","Shree Vishnu","Vishnu standing on the waters with halo, bilingual caption",U,"other","","","good, later print",""),
 ("0336","Shree Ram and Sita","Rama and Sita enthroned with brothers and Hanuman, bilingual caption",U,"other","","","good, later print",""),
 ("0338","Satyanarayan with devotees","Vishnu in a shrine with worshippers and Narada",U,"other","","","good",""),
 ("0339","Hanuman in prayer","Hanuman with folded hands in a landscape",U,"other","","","heavily faded",""),
 ("0341","Ganesha enthroned with two women","Ganesha on his throne with two attendants",U,"other","","","good",""),
 ("0342","Radha and Krishna on a swing","The couple on a swing by moonlight near a waterfall",U,"other","","","good",""),
 ("0343","Krishna's boat ride by moonlight","Krishna with gopis in a boat on the Yamuna at night",U,"other","","","good","Landscape format."),
 ("0344","Krishna with gopis on a terrace","Krishna among women on a palace terrace with peacock",U,"other","","","good","Landscape format."),
 ("0345","Rama, Sita and Lakshmana with the golden deer","The exiles in the forest, the golden deer appears",U,"other","","","good","Landscape format."),
 ("0346","Krishna with gopis in the grove","Krishna with his cow among gopis by the river",U,"other","","","good","Landscape format."),
 ("0347","Night scene in a palace","Sleeping women in a moonlit palace hall, a couple on a couch",U,"other","","","worn frame","Subject still to be identified. Landscape format."),
 ("0348","Krishna and the gopis at the ghat","Krishna by the water, gopis with pots on the steps",U,"other","","","good","Same composition as no. 0541 by V. H. Pandya."),
 ("0350","Krishna with women at a palace pool","Women play and bathe in a courtyard pool, Devanagari caption",U,"other","","","good","Landscape format."),
 ("0351","Coronation of Rama","Rama enthroned with Sita, brothers, Hanuman and sages",U,"other","","","good","Same composition as no. 0051."),
 ("0352","Lakshmi seated on the lotus","Lakshmi seated on a large lotus with elephant and swans",U,"other","","","fair",""),
 ("0353","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","fair",""),
 ("0354","Coronation of Rama with foil mount","Rama and Sita enthroned with attendants, decorative foil surround",U,"other","","","fair",""),
 ("0355","Shankar","Shiva with Parvati, Ganesha, Nandi and lions, signed Ravi Varma, advertising roundel",U,"other","","","losses at the top","Same composition as no. 0544."),
 ("0356","Murugan of Palani","Murugan as young ascetic with staff in his shrine","South India","south","","","good",""),
 ("0357","Hanuman in prayer, advertising print","Hanuman with folded hands and halo","Advertising print for Subbuswami & Sons, Madras, Salem and Coimbatore","south","","","fair",""),
 ("0358","Enthroned goddess with attendants","A goddess under a parasol, attendants with fly whisks and veena",U,"other","","","fair","Same composition as no. 0032."),
 ("0359","Shankar","Shiva with Parvati, Ganesha, Nandi and lions",U,"other","","","pale",""),
 ("0360","Gandhi with Christ","Gandhi in prayer, Christ on the cross and a figure above",U,"other","after 1948","","fair","Memorial print after Gandhi's death, with glitter."),
 ("0361","Nataraja","Shiva as lord of dance with Sivakami, in a temple setting","South India","south","","","good","Same composition as no. 0090."),
 ("0362","Coronation of Rama, embellished","Rama and Sita enthroned among attendants and sages","South India","south","","","good","Hand-embellished."),
 ("0363","Murugan as a child","Bala Murugan with peacock and serpent",  "South India","south","","","good",""),
 ("0364","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","pale",""),
 ("0365","Shiva and Parvati as hunters","Shiva as the Kirata hunter with Parvati, bow and trident",U,"other","","","good","Same composition as no. 0138."),
 ("0366","Adi Shankara with his disciples","The teacher with staff seated among disciples at a hermitage, signed Ravi Varma",U,"other","","","yellowed","Subject probable."),
 ("0367","Krishna, bust","Krishna with peacock-feather crown and halo",U,"other","","","fair",""),
 ("0368","Lakshmi, advertising print","Lakshmi on the lotus with elephant","Advertising print for Vinolia Co. Ltd.","other","","","fair","Vinolia was a British soap maker."),
]
dups7 = {"0331":"0330","0337":"0336","0340":"0339","0349":"0348"}
