K = "Kumkum marks on the glass, not on the print."
S = "small, approx. 25 × 35 cm"
L = "large, approx. 50 × 70 cm"
LQ = "large, landscape"
RVP = "Ravi Varma Press, Karla-Lonavla. Publisher Anant Shivaji Desai, Moti Bazar, Mumbai. Reg. no. "
items = [
 ("0001","Trimurti with devotees","Shiva, Brahma and Vishnu receiving devotees with flower offerings",RVP+"424","rvp","",S,"good",""),
 ("0002","Saraswati, embellished","Saraswati with veena by a river, with peacock and swan","Press unidentified, copyright stamp at the bottom","other","",S,"fair","Hand-embellished with glitter, sequins and beads. Painted frame."),
 ("0003","Shri Virupaksha","Five-headed Shiva with Ganesha, Parvati, Nandi and lion","Ravi Vaibhav F.A.L. Press, Ghatkopar. Publisher A. K. Joshi & Co., Kalbadevi Road, Mumbai. Reg. no. 0081","ghat","Copyright 10.12.1923",S,"horizontal crease across the image",""),
 ("0004","South Indian composite print","Temple deities and scenes from the Ramayana in many panels","South India, probably Madras","south","",S,"water damage along the bottom edge","Embellished with glitter."),
 ("0005","Vishnu on Shesha","Vishnu reclining on the cosmic serpent with Lakshmi, Brahma on the lotus","No press mark visible","other","",S,"good, strong colours",""),
 ("0006","Sulochana","Sulochana receives the head of Indrajit, a scene from the Ramayana",RVP+"581","rvp","",S,"good",""),
 ("0007","Indra Kacheri","The court of Indra, with gold printing",RVP+"582","rvp","",S,"very good",""),
 ("0008","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans, signed Ravi Varma","Probably Ravi Varma Press","other","",S,"water stains, foxing",""),
 ("0009","Ram Darbar","Rama with Sita, Lakshmana and Hanuman","Signature hard to read","other","",S,"heavily yellowed, colour shift",""),
 ("0010","Dashavatara","Vishnu with his ten incarnations in roundels","No press mark visible","other","",S,"flaking, water damage",""),
 ("0011","Krishna with flute","Krishna under a tree with gopis and cows, South Indian style","Ravi Vaibhav F.A.L. Press, Ghatkopar","ghat","",S,"significant losses and stains",""),
 ("0012","Pundalik's pilgrimage","Pundalik carries his wife while his parents walk",RVP+"372","rvp","",S,"print good, glass cracked","Replace the glass so it does not scratch the print."),
 ("0013","Ganesha, advertising print","Ganesha enthroned, with gold embossing","Advertising print for a cloth merchant in Kumbakonam, Tamil Nadu","south","",S,"good",""),
 ("0015","Vishnu with Sridevi and Bhudevi","Vishnu under the serpent hood with both consorts","Ravi Udaya Vijaya Offset Litho, Ghatkopar. Publisher Anant Shivaji Desai, Mumbai. Reg. no. 208","ghat","later offset print",S,"creases, faded",""),
 ("0016","Janaki","Rama and Sita","Ravi Vaibhav Press, Ghatkopar. Publisher A. K. Joshi, Mumbai. Reg. no. 00181","ghat","",S,"fair",""),
 ("0017","Shiva's family with Nandi","Shiva, Parvati and Ganesha enthroned","Press unidentified","other","",S,"heavy water and mould damage","Painted frame."),
 ("0018","Vanvasi Ram","Rama, Sita and Lakshmana in exile, with a deer","Ravi Varma Press, Karla-Lonavla","rvp","",S,"yellowed, damage lower right, frame damaged",""),
 ("0019","Lakshmi, Saraswati and Vishnu","Lakshmi on the lotus, Saraswati in a boat, Vishnu above","No press mark visible","other","",S,"good, fine colours",""),
 ("0020","Savitri","Savitri protects the dying Satyavan from Yama",RVP+"638","rvp","",S,"good",""),
 ("0021","Krishna and Radha, advertising print","Krishna and Radha with water pot, products in the corners","Advertising print, South India","south","",S,"frame damaged, tear at the top",""),
 ("0530","Ram Darbar, large format","Rama with Sita, Lakshmana and Hanuman in a palace","Signed, probably Bangalore","south","",L,"frame worn",K),
 ("0531","Murugan with Valli and Deivanai","Six-headed Murugan with the temples of Palani, Tiruttani and others, Tamil captions","Tamil Nadu","south","",L,"good",K),
 ("0532","Ayodhia Pati Rama","Rama with Sita, Lakshmana and Hanuman","S. S. Brijbasi & Sons, Mathura. Printed in Germany. Artist Narottam Narayan, Nathdwara","brij","",L,"good",K),
 ("0533","Saraswati with foil decoration","Saraswati with veena and peacock","Press unidentified","other","",L,"water damage at the bottom",""),
 ("0534","Mahatma Gandhi","Portrait of Gandhi in a shawl","S. S. Brijbasi & Sons, Karachi. Printed in Germany. Artist M. D. Trivedi","brij","before 1947 (publisher in Karachi)",L,"damage along the bottom edge",K),
 ("0536","Ganesha and Lakshmi","Ganesha enthroned, Lakshmi on the lotus","S. S. Brijbasi & Sons. Artist Narottam Narayan, Nathdwara","brij","",L,"very good",K),
 ("0537","Lakshmi with foil mount","Lakshmi on the lotus with elephant","Ravi Varma composition, press unidentified","other","",L,"tear, damage at the bottom",""),
 ("0538","Goddess with parrot and sugarcane","Enthroned goddess in a temple","Tiruvenkadam, Madurai. Artists C. Kondiah Raju and T. S. Subbiah, Kovilpatti","south","",L,"good",""),
 ("0539","Sree Matha Bhuvaneswari","Bhuvaneswari with three saints, Tamil and English captions","South India, later print","south","approx. 1960s–70s",L,"good",""),
 ("0540","Saraswati with deer","Saraswati with veena, signed Ravi Varma","Probably Ravi Varma Press","other","",L,"tears, losses",""),
 ("0541","Krishna and the gopis at the ghat","Krishna by the water, gopis with pots on the steps","Artist V. H. Pandya","other","1924",LQ,"good",""),
 ("0542","Surdas and Krishna","The blind poet Surdas sings for the young Krishna","Picture Palace, Chowk, Delhi","other","",LQ,"glass broken, heavy creases",K),
 ("0543","Murali Krishna","Krishna with flute by a lake","N. Gopala Row, Cocanada (Kakinada). Printed in Germany","south","",L,"very good",K),
 ("0544","Shankar","Shiva with Parvati, Ganesha, Nandi and lions, signed Ravi Varma","Ravi Varma Press","rvp","",L,"minor damage",K),
 ("0545","Lakshmi, large format","Lakshmi on the lotus with elephant, signed Ravi Varma","Press unidentified","other","",L,"losses at the top",""),
 ("0546","Vishnu on Garuda","Vishnu with Sridevi and Bhudevi riding Garuda","Ravi Varma composition, press unidentified","other","",L,"crease",K),
 ("0548","Saraswati, unframed","Saraswati with veena and peacock","No press mark visible","other","",L,"creases",""),
 ("0549","Saraswati, Malavli","Saraswati with veena and peacock","Ravi Varma F.A.L. Works, Malavli, Poona Dt.","rvp","",L,"tears, losses, unframed","Early print from the original Ravi Varma Press."),
]
