U = "Press not yet identified"
items5 = [
 ("0186","Kaliya Mardana","Krishna dances on the serpent Kaliya",U,"other","","","fair","Same composition as no. 0071."),
 ("0187","Lakshmi and Saraswati with elephants","Lakshmi on the lotus with elephants, Saraswati with veena",U,"other","","","worn",""),
 ("0188","Ranganatha with Venkateswara","Vishnu reclining on Shesha as Ranganatha, Venkateswara and attendants below","South India","south","","","good",""),
 ("0189","Murugan on the peacock","Murugan with Valli and Deivanai on his peacock","South India","south","","","fair",""),
 ("0190","Bharata meets Rama in the forest","Rama, Sita and Lakshmana at the hermitage, Bharata kneeling, a forest dweller in prayer",U,"other","","","faded, worn",""),
 ("0191","Durga on the tiger","Many-armed Durga rides a tiger through the forest, holding a demon's head",U,"other","","","tear lower right",""),
 ("0193","Damayanti and the swan","Damayanti listens to the golden swan, a Ravi Varma composition",U,"other","","","good","Better preserved than no. 0164."),
 ("0194","Radha and Krishna","Radha and Krishna embrace under a tree",U,"other","","","good",""),
 ("0195","Saraswati with peacock","Saraswati with veena in front of an open peacock tail",U,"other","","","good",""),
 ("0196","Court scene with a Brahmin","A seated ruler receives a Brahmin, a queen and courtiers beside",U,"other","","","good","Subject still to be identified."),
 ("0197","Saraswati, advertising print","Saraswati standing on a lotus with peacock and veena","Advertising print for P. R. V. Subramania Chetty, cloth merchant","south","","","good",""),
 ("0198","Krishna and the milkmaid","Krishna meets a gopi with scales and pots by a pond",U,"other","","","good",""),
 ("0199","Murugan with Valli and Deivanai","Murugan and his consorts before an open peacock tail","South India","south","","","good",""),
 ("0200","Portrait of a seated dignitary","A turbaned man on a throne in rich robes",U,"other","","","good","Sitter still to be identified."),
 ("0201","Krishna Tulabharam, calendar","Krishna weighed on the scales, Narada, Rukmini and Satyabhama, with a monthly calendar","South India, Tamil calendar","south","","","fair","Calendar sheet, the year may be readable on the original."),
 ("0202","Ayyappa on the tiger","Ayyappa rides a tiger in the forest","South India","south","","","good",""),
 ("0204","Two deities in twin shrines","Two standing Vishnu figures in twin arched shrines",U,"other","","","good",""),
 ("0205","Krishna with two consorts","Krishna with flute between Rukmini and Satyabhama","South India","south","","","water damage",""),
 ("0206","Krishna with consorts, Tanjore style","Plump Krishna enthroned with two consorts","South India","south","","","good","Same composition as no. 0025."),
 ("0207","Abduction scene","A warrior carries off a woman through a landscape",U,"other","","","good","Subject still to be identified."),
 ("0208","Narasimha","Narasimha kills Hiranyakashipu, Prahlada and women beside",U,"other","","","good","Same composition as no. 0145."),
 ("0209","Krishna with consorts, Tanjore style","Plump Krishna enthroned with two consorts","South India","south","","","fair","Same composition as no. 0025."),
 ("0210","Gajendra Moksha","Vishnu on Garuda rescues the elephant king from the crocodile",U,"other","","","fair",""),
 ("0211","Deity with consorts under a parasol","A standing deity on a lotus between two consorts","South India","south","","","worn frame",""),
 ("0212","Vishnu standing on the waters","Four-armed Vishnu with radiant halo, advertising text at the top","Advertising print, South India","south","","","good",""),
 ("0214","Krishna with two consorts","Krishna between Rukmini and Satyabhama","South India","south","","","faded",""),
 ("0215","Hanuman carries the mountain","Hanuman flies with the mountain of healing herbs",U,"other","","","good",""),
 ("0216","Sulochana","Sulochana receives the head of Indrajit",U,"other","","","good","Same composition as no. 0006."),
 ("0217","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","water stains",""),
 ("0218","Worship of the Shiva linga","Rama, Sita, Lakshmana and Hanuman with the linga, temples behind","South India","south","","","fair",""),
 ("0219","Saraswati","Saraswati with veena and peacock, caption strip visible",U,"other","","","water damage",""),
 ("0220","Hanuman before Ravana","Hanuman sits on his coiled tail facing the ten-headed Ravana",U,"other","","","good","Same composition as no. 0050."),
 ("0221","South Indian composite print","Temple deities and scenes in many panels","South India","south","","","fair",""),
 ("0222","Rama's reunion with Bharata","Rama embraces a young man, Sita, Hanuman and Lakshmana beside, signed Ravi Varma",U,"other","","","fair","Same subject as no. 0137."),
 ("0223","Worship of the Shiva linga","Rama and Sita worship the linga at Rameswaram, with Hanuman and sages","South India","south","","","good",""),
 ("0224","Lakshmi on the lotus, embellished","Lakshmi on the lotus with elephant and swans",U,"other","","","good","Embellished with glitter."),
 ("0225","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",""),
 ("0226","Saraswati, advertising print","Saraswati with veena and peacock, Tamil text at the top","Advertising print, Tamil Nadu","south","","","glass cracked",""),
 ("0227","Krishna the butter thief","The child Krishna crawls towards a bowl of butter",U,"other","","","glass cracked",""),
 ("0228","South Indian composite print","Temple deities and scenes in many panels","South India","south","","","good","Painted frame."),
 ("0229","Yashoda and Krishna","Yashoda with the child Krishna and a cow",U,"other","","","good, later print","Gold foil mount."),
 ("0230","Woman at a dressing table, advertising print","A woman arranging her hair at a mirror","Advertising print for Dralle perfume","other","","","worn","Dralle was a perfume company from Hamburg, a German link in the collection."),
 ("0231","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","yellowed",""),
 ("0232","Dattatreya, advertising print","Three-headed Dattatreya with cow and dogs","Advertising print, South India","south","","","fair","Same composition as no. 0117."),
 ("0233","Vishnu on the waters","Vishnu standing on the ocean under the serpent hood, radiant halo",U,"other","","","good, later print",""),
 ("0234","The child Krishna","The infant Krishna seated with jewellery and crown",U,"other","","","fair",""),
 ("0235","Radha and Krishna","Radha and Krishna embrace under a tree",U,"other","","","good, unframed on mount","Same composition as no. 0194."),
 ("0236","The child Krishna with women","The young Krishna among women in a landscape",U,"other","","","fair","Small landscape format."),
 ("0237","Shakuntala's love letter","Shakuntala lies on the grass writing to Dushyanta, her friends beside her",U,"other","","","fair","A famous Ravi Varma composition. Landscape format."),
 ("0238","Palani hill temple","The hill temple of Murugan at Palani","South India","south","","","fair, unframed",""),
 ("0239","The Great Mosque of Mecca","View of the Masjid al-Haram with the Kaaba",U,"other","","","water stains","One of the few non-Hindu subjects in the collection."),
 ("0240","Rama and Sita enthroned","Rama and Sita with Lakshmana, Bharata and Hanuman under a canopy",U,"other","","","worn frame",""),
 ("0241","Gayatri","Five-headed Gayatri standing on a lotus, Devanagari text",U,"other","","","good, unframed",""),
 ("0242","Enthroned goddess with attendants","A goddess under a parasol, attendants with fly whisks and veena",U,"other","","","good, unframed","Same composition as no. 0032."),
 ("0243","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","fair",""),
 ("0244","Scenes from Krishna's childhood","The child Krishna in the centre, episodes of his youth around him",U,"other","","","fair, later print",""),
 ("0245","Radha and Krishna with gopis","Radha and Krishna on a lotus under a tree, gopis with fly whisks",U,"other","","","good",""),
]
dups5 = {"0192":"0191","0203":"0202","0213":"0212"}
