U = "Press not yet identified"
K = "Kumkum marks on the glass, not on the print."
items10 = [
 ("0490","European battle scene","Infantry and cavalry in close combat on a hillside",U,"other","","","fair","A European print. Landscape format."),
 ("0491","European queens and princesses","Portrait busts of European royal women in rows",U,"other","","","fair","A European print. Landscape format."),
 ("0493","The Kaaba in Mecca","Pilgrims around the Kaaba in the Great Mosque",U,"other","","","good","Landscape format. Related to no. 0239."),
 ("0494","Departure in a royal chariot","A prince leaves a palace in a chariot drawn by white horses, caption at the bottom",U,"other","","","glass cracked","Subject still to be identified. Landscape format."),
 ("0495","Portrait photograph of a Tamil politician","A colour photograph of a woman in a dark sari, probably J. Jayalalithaa","Modern photograph","other","late 20th century","","good","Not a print but a photograph."),
 ("0496","Krishna, bust","Krishna with peacock-feather crown",U,"other","","","torn edges","Same composition as no. 0367."),
 ("0497","Krishna with peacock, advertising calendar","Krishna with flute beside a peacock, portraits of the proprietors","Advertising calendar for K. A. Shunmugavel Beedi Company, Ambasamudram","south","","","good","Tamil Nadu."),
 ("0498","Vishnu on Garuda","Vishnu with Sridevi and Bhudevi riding Garuda, signed Ravi Varma",U,"other","","","fair","Same composition as no. 0546."),
 ("0499","Sita Pati Rama","Rama with Sita, Lakshmana and Hanuman on a tiled floor, caption",U,"other","","","good, later print",""),
 ("0500","Colour photograph of a mother and child","A smiling woman carries a basket and a child in a field","Modern photograph","other","","","good","Not a print but a photograph. Landscape format."),
 ("0501","Meenakshi and Sundareswarar","The goddess and Shiva of Madurai in twin shrines, Ganesha and Nandi below, Devanagari captions","South India","south","","","good","Identifies the subject of no. 0062."),
 ("0502","Deity with two consorts","A standing deity between two consorts in a temple setting","South India","south","","","losses",""),
 ("0503","Deity in a temple gateway","A standing deity in a temple gateway, with cherubs above","South India","south","","","fair","Same composition as no. 0085."),
 ("0504","Warrior on horseback","A rider with shield on a caparisoned horse before buildings",U,"other","","","faded","Landscape format."),
 ("0505","Vishnu with Sridevi and Bhudevi, advertising print","Vishnu under the serpent hood, text 'Support Nation's Own Industry'","Advertising print for The Southern India Confectionery Factory, V. S. & Sons, Kumbakonam","south","","","fair","Swadeshi advertising."),
 ("0506","Indira Gandhi","Portrait with facsimile signature, artist C. N. Row",U,"other","","","good",""),
 ("0507","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",""),
 ("0508","Rasa Lila by moonlight","Many Krishnas dance with the gopis on a moonlit riverbank",U,"other","","","good","Same composition as no. 0278. Landscape format."),
 ("0509","Ganesha enthroned","Ganesha on his throne with lamps and offerings",U,"other","","","faded, later print",K),
 ("0510","Saraswati","Saraswati with veena and peacock",U,"other","","","fair, later print","Scalloped wooden frame. "+K),
 ("0511","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","glass cracked",K),
 ("0512","Krishna with gopis, Glaxo calendar","Krishna with gopis under a tree, calendar for 1932","Advertising calendar for Glaxo, 'Builds Bonnie Babies'","other","1932","","worn frame","Dated 1932. "+K),
 ("0514","Goddess, advertising print","A four-armed goddess, bust, product tins in the corners","Advertising print, publisher still to be identified","other","","","worn frame",K),
 ("0515","Vishnu with his consorts in the water","Vishnu standing on the serpent, two consorts with flowers at his sides",U,"other","","","good",K),
 ("0517","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",K),
 ("0518","Lakshmi on the lotus, shaped mount","Lakshmi on the lotus with elephant, cut to a shaped outline",U,"other","","","good",K),
 ("0520","Krishna in the Om","The child Krishna framed by the sacred syllable, foil decoration",U,"other","","","fair",K),
 ("0521","Krishna with two consorts","Krishna between Rukmini and Satyabhama, caption",U,"other","","","good",K),
 ("0523","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","good",""),
 ("0525","Saraswati","Saraswati with veena and peacock, caption 'Saraswati'",U,"other","","","good",K),
 ("0526","Murugan with Valli and Deivanai","Murugan and his consorts with peacock and serpent","Tamil Nadu","south","","","faded",K),
 ("0527","Murugan with Valli and Deivanai","Murugan and his consorts with the temples of his shrines behind","Tamil Nadu","south","","","faded",K+" Same composition as no. 0531."),
 ("0529","Saraswati","Saraswati with veena and peacock, caption 'Saraswati'",U,"other","","","good",K),
]
dups10 = {"0513":"0512","0516":"0515","0519":"0518","0522":"0521","0524":"0523","0528":"0527"}
PORTRAITS = ["0046","0150","0200","0285","0360","0436","0441","0442","0443","0444","0495","0506","0534","0535"]
