U = "Press not yet identified"
items8 = [
 ("0369","Shaibya's grief","Queen Shaibya in grief with attendants, from the story of Harishchandra, English and Devanagari caption",U,"other","","","heavy water damage","Photographed sideways. Landscape format."),
 ("0370","Vishnu with Sridevi and Bhudevi","Vishnu under the serpent hood with both consorts",U,"other","","","fair","Same composition as no. 0015."),
 ("0371","Worship of the Shiva linga","Rama and Sita worship the linga at Rameswaram, Hanuman flies above","South India","south","","","fair",""),
 ("0372","Ram Darbar","Rama with Sita, Lakshmana and Hanuman before the throne",U,"other","","","good",""),
 ("0373","Ram Darbar","Rama with Sita, Lakshmana and Hanuman before the throne",U,"other","","","good","Same composition as no. 0532."),
 ("0374","Coronation of Rama, advertising print","Rama and Sita enthroned, South Indian captions","Advertising print for Balloon Beedi","south","","","fair",""),
 ("0375","Murugan with gods and devotees","Murugan standing with his consorts, rooster banner, gods and sages in worship","South India","south","","","fair",""),
 ("0376","Vishnu in Vaikuntha","Vishnu with his consorts under the serpent hood, rows of devotees below","South India","south","","","losses",""),
 ("0377","The child Krishna with parrot","The young Krishna with peacock feather holding a parrot",U,"other","","","losses, later print",""),
 ("0378","Shankar","Shiva with Parvati, Ganesha, Nandi and lions",U,"other","","","good","Same composition as no. 0544."),
 ("0379","Saraswati standing","Saraswati with veena standing by the water, swans at her feet",U,"other","","","good",""),
 ("0380","Vishnu with Sridevi and Bhudevi","Vishnu under the serpent hood with both consorts",U,"other","","","good","Same composition as no. 0015."),
 ("0381","Shiva's family in the Himalaya","Shiva and Parvati with Ganesha, Kartikeya and Nandi",U,"other","","","tears, later print",""),
 ("0382","Lakshmi, embellished","Lakshmi on the lotus with elephant, applied fabric sari",U,"other","","","fair","Hand-embellished."),
 ("0384","Ramalinga Swamigal","The Tamil saint in white robes, Tamil captions","Tamil Nadu","south","","","good",""),
 ("0385","Krishna with two consorts","Krishna between Rukmini and Satyabhama","South India","south","","","good",""),
 ("0386","A royal wedding","A couple seated among courtiers and sages, probably Krishna and Rukmini, signed","South India","south","","","good","Subject probable."),
 ("0387","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","good",""),
 ("0388","Vishnu on Garuda","Vishnu with Sridevi and Bhudevi riding Garuda",U,"other","","","good","Same composition as no. 0546."),
 ("0389","Enthroned goddess with attendants","A goddess under a parasol, attendants with fly whisks and veena",U,"other","","","good","Same composition as no. 0032."),
 ("0390","Krishna with flute, gopis and cows","Krishna under a tree between two gopis, cows at his feet","South India","south","","","good",""),
 ("0391","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","good",""),
 ("0392","Yashoda and the child Krishna","Yashoda seated, the young Krishna and Balarama before her",U,"other","","","good",""),
 ("0393","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","pale",""),
 ("0394","Lakshmi, embellished","Lakshmi on the lotus with elephant, applied fabric sari",U,"other","","","fair","Hand-embellished."),
 ("0395","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","good",""),
 ("0396","Satyanarayan with devotees","Vishnu on a pedestal with worshippers and a sage",U,"other","","","good","Same composition as no. 0338."),
 ("0397","Krishna with two consorts","Krishna between Rukmini and Satyabhama","South India","south","","","good",""),
 ("0398","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans, signed",U,"other","","","good",""),
 ("0399","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","heavily faded",""),
 ("0400","Adi Shankara with his disciples","The teacher seated among disciples at a hermitage, signed",U,"other","","","good","Same composition as no. 0366."),
 ("0401","Pilgrims to the mountain goddess","Pilgrims with pots approach a many-armed goddess on the mountain, signed",U,"other","","","good, later print",""),
 ("0403","Vishnu under the serpent hood","Vishnu rising from the water, Gita verse in Devanagari",U,"other","","","good, later print",""),
 ("0404","Murugan on the peacock","Six-headed Murugan with his consorts before a peacock","South India","south","","","good",""),
 ("0405","Saraswati, advertising calendar","Saraswati with veena on a lotus, calendar months at the sides","Advertising calendar for a dyestuffs and chemicals firm, sole agents for India, Burma and Ceylon","other","","","fair","The wording suggests the late 1930s or 1940s."),
 ("0406","Dasharatha's sacrifice","A divine figure rises from the sacrificial fire before a king and priests",U,"other","","","fair","Subject probable."),
 ("0407","Krishna with cows","Krishna seated among cows by a river",U,"other","","","faded",""),
 ("0409","The child Krishna with his parents","The infant Krishna on a couch with Nanda, Yashoda and a woman",U,"other","","","good",""),
 ("0410","Lakshmi, embellished","Lakshmi on the lotus with elephant, applied fabric and sequins, signed",U,"other","","","good","Hand-embellished."),
 ("0411","Woman on a swing","A young woman on a swing above a valley",U,"other","","","faded","Same composition as no. 0084. Embellished."),
 ("0412","Keechaka and Sairandhri","Keechaka approaches Draupadi, disguised as the maid Sairandhri",U,"other","","","fair","A well-known Ravi Varma composition."),
 ("0413","Yashoda and Krishna, advertising print","The child Krishna with Yashoda on a terrace","Advertising print for Gopaljee & Co., asafoetida merchants, Madras","south","","","stains in the lower half",""),
 ("0414","Krishna's birth in the prison","A woman holds the newborn among guards and a bearded man",U,"other","","","fair","Subject probable."),
 ("0415","Saraswati with deer","Saraswati with veena, a deer at her side",U,"other","","","darkened",""),
 ("0416","Radha and Krishna on a swing","The couple on a swing under a tree",U,"other","","","faded",""),
 ("0417","Divine court","A crowned deity with consort enthroned among gods and sages",U,"other","","","fair","Subject still to be identified."),
 ("0418","Krishna with flute and two gopis","Krishna plays under a tree, two women listen, peacock in front",U,"other","","","good",""),
 ("0419","Vishnu on Garuda","Vishnu with Sridevi and Bhudevi riding Garuda",U,"other","","","good","Same composition as no. 0546."),
 ("0420","Krishna with flute, gopis and cows","Krishna under a tree between two gopis, cows at his feet","South India","south","","","fair","Same composition as no. 0390."),
 ("0421","Murugan as a child","Bala Murugan with peacock and serpent","South India","south","","","good","Same composition as no. 0363."),
 ("0422","Sita with Lava and Kusha","Sita shows her sons the target, the boys practise archery","Advertising print, CR monogram","other","","","losses on the left",""),
 ("0424","Goddess enthroned, advertising print","A goddess on a lion throne among devotees","Advertising print for Motor Cycle gold threads, J. N. J.","other","","","fair","Swadeshi advertising for gold thread."),
 ("0425","Krishna with gopis in the grove","Krishna with his cow among gopis by the river",U,"other","","","good","Same composition as no. 0346. Landscape format."),
 ("0426","Rasa Lila by moonlight","Many Krishnas dance with the gopis on a moonlit riverbank",U,"other","","","good","Same composition as no. 0278. Landscape format."),
 ("0427","Krishna and the gopis at the ghat","Krishna by the water, gopis with pots on the steps",U,"other","","","good","Same composition as no. 0541. Small format on mount."),
 ("0428","Ram Darbar, embellished","Rama with Sita, Lakshmana and Hanuman, applied sequins",U,"other","","","frame damaged","Hand-embellished."),
 ("0429","Murugan as a child, advertising print","Bala Murugan with spear and peacock","Advertising print for a snuff brand, South India","south","","","good",""),
]
dups8 = {"0383":"0382","0408":"0407","0423":"0422"}
