U = "Press not yet identified"
items4 = [
 ("0121","Shri Kashi Vishwanath","Bust of Shiva with the Ganga flowing from his hair, four saints in the corners",U,"other","","","fair",""),
 ("0122","Coronation of Rama","Rama and Sita enthroned with brothers, Vasishtha and Hanuman",U,"other","","","worn","Same composition as no. 0049."),
 ("0124","Head of a deity with halo","A crowned deity with radiating halo, sepia tones",U,"other","","","fair, later print",""),
 ("0125","Shiva's family with Nandi","Shiva, Parvati and Ganesha with Nandi and deities",U,"other","","","good","Photographed sideways."),
 ("0126","Kamadhenu with the gods, attacked by a demon","The sacred cow with deities in her body, a demon with sword, Devanagari text",U,"other","","","fair","Photographed sideways. Related to no. 0034."),
 ("0132","Saraswati, embellished","Saraswati with veena and peacock, applied flowers and decoration",U,"other","","","fair","Hand-embellished."),
 ("0133","Kaliya Mardana","Krishna dances on the many-headed Kaliya, the serpent's wives plead",U,"other","","","good",""),
 ("0134","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Garuda and Brahma on the lotus",U,"other","","","worn",""),
 ("0135","South Indian composite print","Temple deities and scenes from the Ramayana in many panels","South India","south","","","good",""),
 ("0136","Ravana abducts Sita, Jatayu attacks","Ravana carries off Sita while the vulture Jatayu attacks him",U,"other","","","good","One of the best-known Ravi Varma compositions."),
 ("0137","Rama's reunion with Bharata","Rama embraces a young man, Sita, Lakshmana and Hanuman beside a fire",U,"other","","","fair","Subject probable, to be confirmed."),
 ("0138","Shiva and Parvati as hunters","Shiva as the Kirata hunter with Parvati, bow and trident",U,"other","","","good",""),
 ("0139","Rama and Sita enthroned","Rama and Sita with Lakshmana and Hanuman under a canopy",U,"other","","","fair, pale colours",""),
 ("0140","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Garuda and Brahma on the lotus",U,"other","","","good",""),
 ("0141","Royal women with an infant prince","Women of the court gather around a queen holding a child",U,"other","","","fair",""),
 ("0142","Worship of the Shiva linga","Rama and Sita worship the linga at Rameswaram, with Hanuman and sages","South India","south","","","good",""),
 ("0143","Murugan on the peacock","Murugan with Valli and Deivanai on his peacock","South India","south","","","good",""),
 ("0144","Bust of a goddess with halo","A crowned goddess with radiating halo",U,"other","","","good",""),
 ("0145","Narasimha","Narasimha kills Hiranyakashipu, Prahlada and women beside",U,"other","","","good",""),
 ("0146","Saraswati with peacock, embellished","Saraswati with veena in front of an open peacock tail",U,"other","","","fair","Embellished with sequins."),
 ("0147","South Indian composite print","Temple deities and scenes in many panels","South India","south","","","fair",""),
 ("0148","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Garuda and Brahma on the lotus",U,"other","","","water stains",""),
 ("0149","South Indian composite print","Temple deities with Ganesha in the centre, scenes in panels","South India","south","","","fair",""),
 ("0150","Portrait of an Indian ruler","A maharaja in state dress with sash and decorations",U,"other","","","fair","Sitter still to be identified."),
 ("0151","Vithoba of Pandharpur","Vithoba standing on his brick, with Garuda and Hanuman",U,"other","","","worn",""),
 ("0152","Gayatri","Five-headed Gayatri on a lotus, mantra in Devanagari around her",U,"other","","","good",""),
 ("0153","Vishnu on the lotus, advertising print","Vishnu standing on a lotus under the serpent hood","Advertising print for V. S. & Sons, Kumbakonam","south","","","good","Same design as no. 0081."),
 ("0154","Krishna with flute, advertising print","Krishna seated with flute, cows behind, prize medals in the corners","Advertising print, publisher still to be identified","other","","","good",""),
 ("0155","Deity in a temple shrine","A standing deity under an ornate temple arch","South India","south","","","fair",""),
 ("0156","Vithoba of Pandharpur, embellished","Vithoba with Garuda and Hanuman",U,"other","","","good","Embellished with sequins."),
 ("0157","Ganesha enthroned","Ganesha on his throne under a parasol",U,"other","","","fair","Same composition as no. 0059."),
 ("0158","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans, caption strip visible",U,"other","","","fair",""),
 ("0159","Murugan on the peacock","Six-headed Murugan with his consorts before a peacock, vignettes in the corners","South India","south","","","good",""),
 ("0160","Gajendra Moksha","Vishnu on Garuda rescues the elephant king from the crocodile",U,"other","","","good",""),
 ("0162","Royal women with an infant prince","Women of the court gather around a queen holding a child",U,"other","","","faded","Same composition as no. 0141."),
 ("0163","Krishna enthroned with a kneeling devotee","Krishna on his throne, courtiers and a kneeling devotee, possibly Sudama",U,"other","","","good","Embellished with sequins."),
 ("0164","Damayanti and the swan","Damayanti listens to the golden swan, a Ravi Varma composition",U,"other","","","heavy water damage",""),
 ("0165","Krishna with his queens","Krishna enthroned among his consorts",U,"other","","","fair",""),
 ("0166","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","worn frame",""),
 ("0167","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Garuda and Brahma on the lotus",U,"other","","","good",""),
 ("0168","Ahalya's deliverance","Ahalya kneels before Rama, Lakshmana and Vishwamitra",U,"other","","","fair",""),
 ("0169","Coronation of Rama","Rama and Sita enthroned with brothers and Hanuman",U,"other","","","fair","Same composition as no. 0080."),
 ("0170","Vishnu with Sridevi and Bhudevi, embellished","Vishnu under the serpent hood with both consorts",U,"other","","","fair","Hand-embellished."),
 ("0171","Rama worships Shiva at Rameswaram","Rama, Sita, Lakshmana and Hanuman worship the Shiva linga",U,"other","","","fair","Same composition as no. 0042."),
 ("0172","Lakshmi and Saraswati with elephants","Lakshmi on the lotus with elephants, Saraswati with veena","Publisher, bookbinder and stationer, Pycroft's Road, Triplicane, Madras","south","","","fair",""),
 ("0173","Goddess with pilgrimage sites","A seated goddess surrounded by panels with temples and deities",U,"other","","","fair",""),
 ("0174","Lakshmi, advertising print","Lakshmi on the lotus in an oval frame","Advertising print for T. S. Ganesa & Co., Tinnevelly Town","south","","","fair",""),
 ("0175","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",""),
 ("0177","Guha ferries Rama across the Ganga","Rama, Sita and Lakshmana in the boatman's sailing boat",U,"other","","","good",""),
 ("0178","Harishchandra and Taramati","Harishchandra raises his sword, Taramati kneels by their dead son, Vishnu appears",U,"other","","","good",""),
 ("0179","Hari-Hara Milan","Vishnu and Lakshmi on an elephant meet Shiva, Parvati and Ganesha on Nandi, signed Ravi Varma",U,"other","","","fair","Subject identified via no. 0311."),
 ("0180","Gajalakshmi, advertising print","Lakshmi standing on the lotus between elephants","Advertising print, Old Tharagupet, Bangalore City","south","","","fair",""),
 ("0181","Krishna and Arjuna in the chariot","Krishna drives Arjuna's chariot into battle",U,"other","","","good",""),
 ("0182","Shrinathji of Nathdwara","The image of Shrinathji in his shrine",U,"other","","","scratches and losses",""),
 ("0183","Coronation of Rama, embellished","Rama and Sita enthroned with brothers and Hanuman",U,"other","","","fair","Hand-embellished."),
 ("0185","Rasa Lila","Krishna dances with the gopis to drums, a temple behind",U,"other","","","good",""),
]
dups4 = {"0123":"0122","0161":"0160","0176":"0175","0184":"0183"}
