U = "Press not yet identified"
items9 = [
 ("0430","Shiva and Parvati in the Himalaya","Shiva kneels before Parvati by a waterfall",U,"other","","","fair",""),
 ("0431","Vishnu appears to a devotee","Vishnu appears to a devotee meditating in the forest",U,"other","","","good","Same composition as no. 0041."),
 ("0432","Lakshmi, embellished","Lakshmi on the lotus with elephant, applied fabric and sequins",U,"other","","","fair","Hand-embellished."),
 ("0433","Anointing of Rama","Rama and Sita are anointed under a parasol, surrounded by the court",U,"other","","","good",""),
 ("0434","Assembly in a pillared hall","Kings and sages gather in a royal hall, a crowned man points",U,"other","","","fair","Subject still to be identified."),
 ("0435","Krishna in a garden, advertising print","Krishna seated in a flower garden","Advertising print for V. Shunmugam & Co., Madras snuff","south","","","good",""),
 ("0436","Portrait of an Indian ruler","A maharaja in state dress with sash and decorations",U,"other","","","good","Same portrait as no. 0150."),
 ("0437","The child Krishna adorned","Women adorn the child Krishna, a king watches",U,"other","","","good",""),
 ("0438","Ranganatha","Vishnu reclining on Shesha, gods and devotees around","South India","south","","","good","Landscape format."),
 ("0439","European battle scene","Cavalry and cannon in battle, a village burning behind",U,"other","","","fair","A European print, unusual in the collection. Landscape format."),
 ("0440","Vishnu with halo","Four-armed Vishnu standing on the clouds",U,"other","","","good, later print",""),
 ("0441","Portrait of an Indian statesman","A man in black sherwani and Gandhi cap with walking stick, probably Rajendra Prasad",U,"other","1950s","","fair","Identification probable."),
 ("0442","Rani of Jhansi","Bust of the queen with sword and shield, Marathi caption",U,"other","","","good","Nationalist subject."),
 ("0443","Subhas Chandra Bose","Bose in the uniform of the Indian National Army",U,"other","1940s","","good","Nationalist portrait."),
 ("0444","Jawaharlal Nehru","Portrait of Nehru in waistcoat and cap",U,"other","","","fair",""),
 ("0445","Shankar","Shiva with Parvati, Ganesha, Nandi and lions, signed Ravi Varma",U,"other","","","good","Same composition as no. 0544."),
 ("0446","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","good",""),
 ("0447","Durga on the tiger","Durga on her tiger before a temple, pilgrims around",U,"other","","","fair, later print",""),
 ("0448","Young woman under a flowering tree","A woman in a pink sari leaning on a blossoming tree",U,"other","","","fair",""),
 ("0449","Two women on a terrace","Two women by a balustrade, one looking away",U,"other","","","darkened",""),
 ("0450","Saraswati standing","Saraswati with veena standing by the water, swans at her feet",U,"other","","","fair","Same composition as no. 0379."),
 ("0451","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","faded",""),
 ("0452","Shiva and Parvati, advertising print","Shiva kneels before Parvati by a waterfall","Advertising print for The Industrial & Prudential Assurance Co., Madras","south","","","fair","Same composition as no. 0430."),
 ("0453","Murugan with peacock","The young Murugan with spear before a peacock","South India","south","","","good",""),
 ("0454","Royal court with offerings","A king enthroned in a pillared hall, courtiers bring gifts",U,"other","","","fair",""),
 ("0455","The child Krishna on a peacock feather","The infant Krishna with butter on a giant peacock feather",U,"other","","","good, later print","Gold foil border."),
 ("0456","Vithoba and Rakhumai","The deities of Pandharpur with saints and temple scenes around them",U,"other","","","good","Same composition as no. 0301."),
 ("0457","Virabhadra at Daksha's sacrifice","A fierce figure with sword at the altar, Sati's spirit above, Nandi",U,"other","","","good","Same composition as no. 0112."),
 ("0458","Vishnu with Sridevi and Bhudevi","Vishnu standing on the serpent, consorts on lotuses",U,"other","","","good, later print","Gold foil border."),
 ("0459","Krishna and Radha in a pavilion","The couple enthroned with attendants, Nathdwara style",U,"other","","","good",""),
 ("0460","Lakshmi seated on the lotus","Lakshmi seated on a large lotus with elephant and swans",U,"other","","","fair","Same composition as no. 0352."),
 ("0461","Murugan on the peacock","Six-headed Murugan with his consorts before a peacock","South India","south","","","good",""),
 ("0462","Dattatreya seated","Three-headed Dattatreya seated with cow and dogs, advertising roundel",U,"other","","","good",""),
 ("0464","Dattatreya with cow and dogs","Three-headed Dattatreya standing, advertising roundel at the top",U,"other","","","fair","Same composition as no. 0117."),
 ("0465","Satyanarayan with devotees","Vishnu in a shrine with worshippers and Narada",U,"other","","","good","Same composition as no. 0338."),
 ("0466","Shiva blesses his devotees","Shiva seated on a rock beneath a tree, devotees around him",U,"other","","","tear top left",""),
 ("0467","Krishna with flute, gopis and cows","Krishna under a tree between two gopis, cows at his feet","South India","south","","","good","Same composition as no. 0390."),
 ("0468","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",""),
 ("0469","Lakshmi on the lotus","Lakshmi on the lotus with elephant and swans",U,"other","","","fair",""),
 ("0470","Ahalya's deliverance","Ahalya bows before Rama, Lakshmana and Vishwamitra",U,"other","","","fair",""),
 ("0471","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",""),
 ("0472","Parvati with child, advertising print","A goddess seated with a child by a waterfall, peacock and lion","Advertising print for Sri Ambal & Co., Madras","south","","","fair",""),
 ("0473","Goddess in a temple shrine","A standing goddess in a carved stone shrine","South India","south","","","tear",""),
 ("0474","Lakshmi seated on the lotus","Lakshmi seated on a large lotus with elephant and swans",U,"other","","","good","Same composition as no. 0352."),
 ("0475","Vishnu on Garuda","Vishnu with Sridevi and Bhudevi riding Garuda above a landscape",U,"other","","","fair",""),
 ("0476","Rama lifts Shiva's bow, advertising print","Rama with the great bow at Sita's bridegroom contest","Advertising print for a dyestuffs firm, Bombay","other","","","water damage",""),
 ("0477","Shankar","Shiva with Parvati, Ganesha, Nandi and lions, advertising roundel",U,"other","","","good","Same composition as no. 0544."),
 ("0478","Vishnu on Garuda","Vishnu with Sridevi and Bhudevi riding Garuda, advertising label",U,"other","","","good","Same composition as no. 0546."),
 ("0479","Coronation of Rama","Rama and Sita enthroned with brothers and Hanuman",U,"other","","","losses","Same composition as no. 0080."),
 ("0480","Vishnu on the serpent, advertising print","The young Vishnu on Shesha in the ocean","Advertising print for Dr. G. B.'s Medicated Snuff, Guru Basava & Co., Madras","south","","","good",""),
 ("0481","Enthroned goddess","A richly adorned goddess under a serpent hood","South India","south","","","losses at the edges",""),
 ("0482","Shantanu and Satyavati","A king at the water's edge with a young woman seated on a rock",U,"other","","","heavy losses","Subject probable, after a Ravi Varma painting."),
 ("0483","The child Krishna on a peacock feather","The infant Krishna with butter on a giant peacock feather",U,"other","","","good","Same composition as no. 0455."),
 ("0484","Deity in a temple arch","A standing four-armed deity under an ornate arch","South India","south","","","fair",""),
 ("0485","Ram Darbar","Rama with Sita, Lakshmana and Hanuman before the throne",U,"other","","","worn frame","Same composition as no. 0532."),
 ("0486","Saraswati","Saraswati with veena and peacock by a river",U,"other","","","good",""),
 ("0487","The child Krishna","The infant Krishna seated in an oval frame",U,"other","","","fair","Same composition as no. 0234."),
 ("0488","Krishna with cows, advertising print","Krishna leaning on a tree with cows and peacock","Advertising print for gripe water","other","","","fair",""),
 ("0489","Vishnu reclining with the gods","Vishnu on Shesha surrounded by gods and devotees","South India","south","","","water damage","Landscape format."),
]
dups9 = {"0463":"0462"}
