U = "Press not yet identified"
C = "Condition from overview photo, to be checked"
items2 = [
 ("0022","Apsara in the clouds","A celestial nymph floating in the clouds with a ball, probably Urvashi or Tilottama",U,"other","","", "good","Nude studies like this are rare among Ravi Varma compositions."),
 ("0023","Lakshmi with elephants","Lakshmi with elephants and peacock",U,"other","","", "photographed sideways",""),
 ("0024","Lakshmi and Saraswati with elephants","Lakshmi on the lotus with elephants, Saraswati with veena and peacock",U,"other","","", "fair, frame worn",""),
 ("0025","Krishna with consorts, Tanjore style","Plump Krishna enthroned with two consorts, in the style of Tanjore painting","South India","south","","", "fair",""),
 ("0026","Ahalya's deliverance","Rama frees Ahalya from the curse, with Vishwamitra and Lakshmana",U,"other","","", "fair","Embellished with sequins."),
 ("0027","Adi Shankara with his disciples","The teacher seated among disciples by a pond at a hermitage",U,"other","","", "water damage","Subject probable, same composition as no. 0366."),
 ("0028","Vishnu with Sridevi and Bhudevi, embellished","Vishnu under the serpent hood with both consorts",U,"other","","", "fair","Embellished. Same composition as no. 0015."),
 ("0029","Navagraha","The nine planetary deities, Surya in the centre",U,"other","","", "fair","Painted frame."),
 ("0030","Hanuman carrying Rama and Lakshmana","Hanuman flies with Rama and Lakshmana on his shoulders",U,"other","","", "good",""),
 ("0031","Krishna's boat ride","Krishna with gopis in a boat under a parasol",U,"other","","", "good",""),
 ("0032","Enthroned goddess with attendants","A goddess under a parasol, attendants with fly whisks and veena",U,"other","","", "fair","Possibly embellished."),
 ("0033","Deity and Narada at an altar","A four-armed deity and Narada with veena before an offering table",U,"other","","", "good",""),
 ("0034","Kamadhenu, the cow of the gods","The sacred cow with deities in her body, Marathi text",U,"other","","", "worn","Politically charged motif from the cow-protection movement around 1890."),
 ("0037","Vishnu on the banyan leaf","Infant Vishnu on a banyan leaf, surrounded by scenes in roundels",U,"other","","", "good",""),
 ("0039","Mother with dead child before an ascetic","A grieving mother with her child, a dead boy on the ground, an ascetic with staff",U,"other","","", "good","Story still to be identified."),
 ("0041","Vishnu appears to a devotee","Vishnu appears to a devotee meditating in the forest",U,"other","","", "worn",""),
 ("0042","Rama worships Shiva at Rameswaram","Rama, Sita, Lakshmana and Hanuman worship the Shiva linga, sages at the fire",U,"other","","", "fair",""),
 ("0044","Shiva's family with gods","Shiva and Parvati with the child Ganesha, flanked by deities",U,"other","","", "faded",""),
 ("0045","Varaha","Vishnu's boar incarnation lifts the earth from the ocean",U,"other","","", "good",""),
 ("0046","United We Stand","Nehru embracing Zhou Enlai, surrounded by world leaders of the 1950s","Political print, publisher not yet identified","other","1950s","", "fair","Political poster from the time of the Non-Aligned Movement."),
 ("0047","Matsya","Vishnu's fish incarnation rescues the Vedas",U,"other","","", "good",""),
 ("0048","Yama's court","Yama on his buffalo leads souls before the court of the dead",U,"other","","", "good",""),
 ("0049","Coronation of Rama","Rama and Sita enthroned with brothers, Vasishtha and Hanuman",U,"other","","", "good",""),
 ("0050","Hanuman before Ravana","Hanuman sits on his coiled tail facing the ten-headed Ravana",U,"other","","", "fair",""),
 ("0051","Coronation of Rama","Rama enthroned with Sita, brothers, Hanuman and sages",U,"other","","", "faded",""),
 ("0052","Ganga and Bhagiratha","The goddess Ganga on her crocodile, the sage Bhagiratha in prayer",U,"other","","", "good",""),
 ("0053","Krishna with flute","Krishna under the tree with gopis and cows, South Indian style",U,"other","","", "fair","Same composition as no. 0011."),
 ("0054","Krishna with flute","Krishna under the tree with gopis and cows, South Indian style",U,"other","","", "good","Same composition as no. 0011."),
 ("0055","Vishnu on Shesha","Vishnu on the serpent with Lakshmi, Garuda and Brahma on the lotus",U,"other","","", "fair",""),
 ("0056","Gayatri","Five-headed Gayatri on a lotus, with smaller scenes in the corners",U,"other","","", "fair","Painted frame."),
 ("0058","Lakshmi, embellished","Lakshmi on the lotus with elephant, applied decoration",U,"other","","", "fair","Hand-embellished."),
 ("0059","Ganesha enthroned","Ganesha on his throne under a parasol",U,"other","","", "good",""),
 ("0060","Venkateswara of Tirupati","The deity of Tirupati in his temple shrine","South India","south","","", "fair",""),
 ("0061","Venkateswara of Tirupati","The deity of Tirupati in his temple shrine","South India","south","","", "fair","Same composition as no. 0060."),
 ("0062","Meenakshi and Sundareswarar","The goddess and Shiva of Madurai in twin shrines, Nandi in front","South India","south","","", "fair",""),
 ("0063","Saraswati","Saraswati with veena and peacock by a river",U,"other","","", "good, strong colours",""),
 ("0064","Surya","The sun god in his chariot drawn by seven horses",U,"other","","", "good",""),
 ("0065","Krishna with peacock, advertising print","Krishna with flute beside a peacock","Advertising print for Sri Ramakrishna Vilas, Kumbakonam","south","","", "good",""),
 ("0066","Worship of the Shiva linga","Rama and Sita worship the linga under a serpent hood, with sages","South India","south","","", "damaged","Embellished."),
 ("0067","Nataraja","Shiva as lord of dance in a temple setting","South India","south","","", "severe damage in the upper half",""),
 ("0068","Enthroned goddess with attendants","A goddess under a parasol, attendants with fly whisks and veena",U,"other","","", "crack in the glass","Same composition as no. 0032."),
 ("0069","Durga slays Mahishasura","Durga on her lion kills the buffalo demon",U,"other","","", "good",""),
 ("0070","Gajalakshmi","Lakshmi seated on the lotus, bathed by two elephants",U,"other","","", "good",""),
 ("0071","Kaliya Mardana","Krishna dances on the serpent Kaliya",U,"other","","", "good",""),
 ("0072","Woman with halo and book","A crowned woman with peacock feather, holding a book",U,"other","","", "fair","Subject still to be identified."),
]
dups2 = {"0038":"0037","0040":"0039","0043":"0042"}
